ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'TURKIYE_EGITIM_SORUMLUSU';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'TURKIYE_UNIVERSITE_SORUMLUSU';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'TURKIYE_LISE_SORUMLUSU';
