UPDATE "User"
SET role = CASE
  WHEN sistem = 'EGITIMCI'   THEN 'TURKIYE_EGITIM_SORUMLUSU'::"Role"
  WHEN sistem = 'UNIVERSITE' THEN 'TURKIYE_UNIVERSITE_SORUMLUSU'::"Role"
  WHEN sistem = 'LISE'       THEN 'TURKIYE_LISE_SORUMLUSU'::"Role"
  ELSE 'TURKIYE_EGITIM_SORUMLUSU'::"Role"
END
WHERE role = 'TURKIYE_SORUMLUSU';

UPDATE "Invitation"
SET role = 'TURKIYE_EGITIM_SORUMLUSU'::"Role"
WHERE role = 'TURKIYE_SORUMLUSU';

UPDATE "RoleAssignment"
SET role = 'TURKIYE_EGITIM_SORUMLUSU'::"Role"
WHERE role = 'TURKIYE_SORUMLUSU';
