import { prisma } from "./prisma";

interface AuditParams {
  userId: string;
  action: string;
  entity: string;
  entityId?: string;
  oldValue?: object;
  newValue?: object;
  ipAddress?: string;
  description?: string;
}

export async function createAuditLog(params: AuditParams) {
  return prisma.auditLog.create({
    data: {
      userId: params.userId,
      action: params.action,
      entity: params.entity,
      entityId: params.entityId,
      oldValue: params.oldValue ?? undefined,
      newValue: params.newValue ?? undefined,
      ipAddress: params.ipAddress,
      description: params.description,
    },
  });
}

export const ACTIONS = {
  USER_CREATED: "KULLANICI_OLUSTURULDU",
  USER_INVITED: "KULLANICI_DAVET_EDILDI",
  USER_APPROVED: "KULLANICI_ONAYLANDI",
  USER_REJECTED: "KULLANICI_REDDEDILDI",
  PASSWORD_SET: "SIFRE_OLUSTURULDU",
  ROLE_CHANGED: "ROL_DEGISTIRILDI",
  IL_ASSIGNED: "IL_ATANDI",
  BOLGE_ASSIGNED: "BOLGE_ATANDI",
  TASK_TRANSFERRED: "GOREV_DEVRI_YAPILDI",
  USER_DEACTIVATED: "KULLANICI_PASIFLESTIRILDI",
  ACTIVITY_CREATED: "FAALIYET_OLUSTURULDU",
  ACTIVITY_UPDATED: "FAALIYET_GUNCELLENDI",
  ACTIVITY_DELETED: "FAALIYET_SILINDI",
  BURS_STATUS_CHANGED: "BURS_DURUM_GUNCELLENDI",
  EKKAYIT_STATUS_CHANGED: "EK_KAYIT_DURUM_GUNCELLENDI",
  FEEDBACK_STATUS_CHANGED: "GERIBILDIRIM_DURUM_GUNCELLENDI",
  TARGET_CREATED: "HEDEF_OLUSTURULDU",
  TARGET_UPDATED: "HEDEF_GUNCELLENDI",
  PASSWORD_RESET: "SIFRE_SIFIRLANDI",
  HOUSING_UNIT_CREATED:  "BARINMA_BIRIM_OLUSTURULDU",
  HOUSING_UNIT_UPDATED:  "BARINMA_BIRIM_GUNCELLENDI",
  HOUSING_UNIT_DELETED:  "BARINMA_BIRIM_SILINDI",
  HOUSING_STUDENT_SAVED:   "BARINMA_OGRENCI_KAYDEDILDI",
  HOUSING_STUDENT_DELETED: "BARINMA_OGRENCI_SILINDI",
  HOUSING_VISIT_CREATED:  "BARINMA_ZIYARET_EKLENDI",
  HOUSING_VISIT_DELETED:  "BARINMA_ZIYARET_SILINDI",
  DOC_FOLDER_CREATED: "DOKUMAN_KLASOR_OLUSTURULDU",
  DOC_FOLDER_UPDATED: "DOKUMAN_KLASOR_GUNCELLENDI",
  DOC_FOLDER_DELETED: "DOKUMAN_KLASOR_SILINDI",
  DOC_UPLOADED:       "DOKUMAN_YUKLENDI",
  DOC_UPDATED:        "DOKUMAN_GUNCELLENDI",
  DOC_DELETED:        "DOKUMAN_SILINDI",
  DOC_SHARED:         "DOKUMAN_PAYLASIM_OLUSTURULDU",
  FORM_CREATED:   "FORM_OLUSTURULDU",
  FORM_UPDATED:   "FORM_GUNCELLENDI",
  FORM_PUBLISHED: "FORM_YAYINLANDI",
  FORM_CLOSED:    "FORM_KAPATILDI",
  FORM_DELETED:   "FORM_SILINDI",
  FORM_ANSWERED:  "FORM_YANITLANDI",
  PERIOD_ARCHIVED:   "DONEM_ARSIVLENDI",
  PERIOD_UNARCHIVED: "DONEM_ARSIVDEN_CIKARILDI",
};
